# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/manu/Applicazioni/SuperBoucle-Manu/superboucle/preferences_ui.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(584, 551)
        self.groupBoxClips = QtWidgets.QGroupBox(Dialog)
        self.groupBoxClips.setGeometry(QtCore.QRect(9, 291, 566, 221))
        self.groupBoxClips.setObjectName("groupBoxClips")
        self.cBoxShowDetailsWhenTriggered = QtWidgets.QCheckBox(self.groupBoxClips)
        self.cBoxShowDetailsWhenTriggered.setGeometry(QtCore.QRect(20, 30, 341, 29))
        self.cBoxShowDetailsWhenTriggered.setObjectName("cBoxShowDetailsWhenTriggered")
        self.cBoxPlayAfterRecord = QtWidgets.QCheckBox(self.groupBoxClips)
        self.cBoxPlayAfterRecord.setEnabled(True)
        self.cBoxPlayAfterRecord.setGeometry(QtCore.QRect(20, 110, 331, 29))
        self.cBoxPlayAfterRecord.setObjectName("cBoxPlayAfterRecord")
        self.labelRecordingColor = QtWidgets.QLabel(self.groupBoxClips)
        self.labelRecordingColor.setEnabled(True)
        self.labelRecordingColor.setGeometry(QtCore.QRect(23, 145, 191, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelRecordingColor.sizePolicy().hasHeightForWidth())
        self.labelRecordingColor.setSizePolicy(sizePolicy)
        self.labelRecordingColor.setObjectName("labelRecordingColor")
        self.rButtonAmberRecColor = QtWidgets.QRadioButton(self.groupBoxClips)
        self.rButtonAmberRecColor.setEnabled(True)
        self.rButtonAmberRecColor.setGeometry(QtCore.QRect(210, 150, 351, 29))
        self.rButtonAmberRecColor.setChecked(True)
        self.rButtonAmberRecColor.setObjectName("rButtonAmberRecColor")
        self.rButtonRedRecColor = QtWidgets.QRadioButton(self.groupBoxClips)
        self.rButtonRedRecColor.setEnabled(True)
        self.rButtonRedRecColor.setGeometry(QtCore.QRect(210, 190, 351, 29))
        self.rButtonRedRecColor.setObjectName("rButtonRedRecColor")
        self.cBoxShowDetailsWhenVolumeChanged = QtWidgets.QCheckBox(self.groupBoxClips)
        self.cBoxShowDetailsWhenVolumeChanged.setGeometry(QtCore.QRect(20, 70, 451, 29))
        self.cBoxShowDetailsWhenVolumeChanged.setObjectName("cBoxShowDetailsWhenVolumeChanged")
        self.groupBoxGrid = QtWidgets.QGroupBox(Dialog)
        self.groupBoxGrid.setGeometry(QtCore.QRect(10, 210, 566, 71))
        self.groupBoxGrid.setObjectName("groupBoxGrid")
        self.labelDefaultSize = QtWidgets.QLabel(self.groupBoxGrid)
        self.labelDefaultSize.setEnabled(True)
        self.labelDefaultSize.setGeometry(QtCore.QRect(27, 20, 201, 31))
        self.labelDefaultSize.setObjectName("labelDefaultSize")
        self.spinRows = QtWidgets.QSpinBox(self.groupBoxGrid)
        self.spinRows.setEnabled(True)
        self.spinRows.setGeometry(QtCore.QRect(430, 30, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinRows.setFont(font)
        self.spinRows.setMinimum(1)
        self.spinRows.setMaximum(8)
        self.spinRows.setProperty("value", 8)
        self.spinRows.setObjectName("spinRows")
        self.spinColumns = QtWidgets.QSpinBox(self.groupBoxGrid)
        self.spinColumns.setEnabled(True)
        self.spinColumns.setGeometry(QtCore.QRect(280, 30, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spinColumns.setFont(font)
        self.spinColumns.setMinimum(1)
        self.spinColumns.setMaximum(8)
        self.spinColumns.setProperty("value", 8)
        self.spinColumns.setObjectName("spinColumns")
        self.labelHG = QtWidgets.QLabel(self.groupBoxGrid)
        self.labelHG.setGeometry(QtCore.QRect(430, 10, 101, 21))
        self.labelHG.setObjectName("labelHG")
        self.labelVG = QtWidgets.QLabel(self.groupBoxGrid)
        self.labelVG.setGeometry(QtCore.QRect(280, 10, 111, 21))
        self.labelVG.setObjectName("labelVG")
        self.groupBoxConnections = QtWidgets.QGroupBox(Dialog)
        self.groupBoxConnections.setGeometry(QtCore.QRect(9, 9, 561, 65))
        self.groupBoxConnections.setObjectName("groupBoxConnections")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBoxConnections)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cBoxAutoconnect = QtWidgets.QCheckBox(self.groupBoxConnections)
        self.cBoxAutoconnect.setObjectName("cBoxAutoconnect")
        self.verticalLayout.addWidget(self.cBoxAutoconnect)
        self.groupBoxPerformance = QtWidgets.QGroupBox(Dialog)
        self.groupBoxPerformance.setGeometry(QtCore.QRect(10, 90, 566, 121))
        self.groupBoxPerformance.setObjectName("groupBoxPerformance")
        self.cBoxShowScenesManager = QtWidgets.QCheckBox(self.groupBoxPerformance)
        self.cBoxShowScenesManager.setGeometry(QtCore.QRect(20, 40, 431, 29))
        self.cBoxShowScenesManager.setObjectName("cBoxShowScenesManager")
        self.cBoxShowPlaylistManager = QtWidgets.QCheckBox(self.groupBoxPerformance)
        self.cBoxShowPlaylistManager.setGeometry(QtCore.QRect(20, 80, 481, 29))
        self.cBoxShowPlaylistManager.setObjectName("cBoxShowPlaylistManager")
        self.labelMessage = QtWidgets.QLabel(Dialog)
        self.labelMessage.setGeometry(QtCore.QRect(10, 520, 561, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelMessage.setFont(font)
        self.labelMessage.setStyleSheet("color: rgb(255, 0, 0);")
        self.labelMessage.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelMessage.setObjectName("labelMessage")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Preferences"))
        self.groupBoxClips.setTitle(_translate("Dialog", "Clips"))
        self.cBoxShowDetailsWhenTriggered.setText(_translate("Dialog", "Show clip details when triggered on / off"))
        self.cBoxPlayAfterRecord.setText(_translate("Dialog", "Start playing a clip immediately after recording"))
        self.labelRecordingColor.setText(_translate("Dialog", "Cell color for recording clips"))
        self.rButtonAmberRecColor.setText(_translate("Dialog", "AMBER for recording (RED for idle clip) (default)"))
        self.rButtonRedRecColor.setText(_translate("Dialog", "RED for recording (AMBER for idle clip)"))
        self.cBoxShowDetailsWhenVolumeChanged.setText(_translate("Dialog", "Show clip details when clip volume is changed from MIDI controller"))
        self.groupBoxGrid.setTitle(_translate("Dialog", "Grid"))
        self.labelDefaultSize.setText(_translate("Dialog", "Default grid size for new songs"))
        self.labelHG.setText(_translate("Dialog", "Lines (Height)"))
        self.labelVG.setText(_translate("Dialog", "Columns (Width)"))
        self.groupBoxConnections.setTitle(_translate("Dialog", "Connections"))
        self.cBoxAutoconnect.setText(_translate("Dialog", "Autoconnect main ports on program start"))
        self.groupBoxPerformance.setTitle(_translate("Dialog", "Performance"))
        self.cBoxShowScenesManager.setText(_translate("Dialog", "Show scenes window on start up"))
        self.cBoxShowPlaylistManager.setText(_translate("Dialog", "Show playlist window on start up"))
        self.labelMessage.setText(_translate("Dialog", "message"))
